/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewGUI;

/**
 */
public class VistaRequerimientoReto5 extends javax.swing.JFrame {

    /**
     * Creates new form VistaRequerimientoReto5
     */
    public VistaRequerimientoReto5() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("REQUERIMIENTOS");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRequerimiento2 = new javax.swing.JButton();
        BtnRequerimiento3 = new javax.swing.JButton();
        BtnRequerimiento1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRequerimiento2.setBackground(new java.awt.Color(102, 102, 255));
        BtnRequerimiento2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnRequerimiento2.setText("Requerimiento 2");
        BtnRequerimiento2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRequerimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequerimiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRequerimiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 80));

        BtnRequerimiento3.setBackground(new java.awt.Color(0, 255, 0));
        BtnRequerimiento3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnRequerimiento3.setText("Requerimiento 3");
        BtnRequerimiento3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRequerimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequerimiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRequerimiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 110, 80));

        BtnRequerimiento1.setBackground(new java.awt.Color(255, 255, 102));
        BtnRequerimiento1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnRequerimiento1.setText("Requerimiento 1");
        BtnRequerimiento1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRequerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequerimiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRequerimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRequerimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequerimiento2ActionPerformed
       VistaRequerimiento2 vr = new VistaRequerimiento2();
    vr.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_BtnRequerimiento2ActionPerformed

    private void BtnRequerimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequerimiento3ActionPerformed
       VistaRequerimiento3 vr = new VistaRequerimiento3();
    vr.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_BtnRequerimiento3ActionPerformed

    private void BtnRequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequerimiento1ActionPerformed
    VistaRequerimiento1 vr = new VistaRequerimiento1();
    vr.setVisible(true);
    }//GEN-LAST:event_BtnRequerimiento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientoReto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRequerimiento1;
    private javax.swing.JButton BtnRequerimiento2;
    private javax.swing.JButton BtnRequerimiento3;
    // End of variables declaration//GEN-END:variables
}
